# file: docker-compose.yml
# #
# # Container mit PSQL und NGINX
# #
# # Amna Mamund, Maryana Bucknell, Rona Istrefi
# #
# ###################################

services:
  db:
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: quiz-api-secret
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: quiz-api-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_HOST_AUTH_METHOD
      valueFrom:
        secretKeyRef:
          name: quiz-api-secret
          key: POSTGRES_HOST_AUTH_METHOD
    container_name: pg_container
    image: postgres:latest
    restart: always
    networks:
     - pgnetwork
    ports:
      - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data/:rw

  pgadmin:
    env:
      - name: PGADMIN_DEFAULT_EMAIL
        valueFrom:
          secretKeyRef:
            name: quiz-api-secret
            key: PGADMIN_DEFAULT_EMAIL
      - name: PGADMIN_DEFAULT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: quiz-api-secret
            key: PGADMIN_DEFAULT_PASSWORD
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - pgnetwork
    ports:
      - "8081:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin/:rw

networks:
  pgnetwork: 
    driver: bridge
              
volumes:
  pgadmin-data:
  postgres-data:
